### ISSUE TITLE
get_list params question

### ISSUE THREAD

**Issue by karindalziel** [CDRH/data#65]
I'd like clarification on how params work for the get_text function described in tei_to_es.md:

`get_text` and `get_list` accept a few parameters.

- xpath(s) : a string or array of strings
- keep_tags : defaults to false, pass in true if you want to convert italics, bold, underline to HTML

`get_text` only:

- delimiter : the separator between multiple items for get_text

```ruby
get_text "/TEI/person", false, ","
#=> "Jadzia Dax, Geordi LaForge"

get_text @xpaths["people"], false, " &"
#=> "Jadzia Dax & Geordi LaForge"
```

The question is: do you have to pass in these params in a particular order, and do all always need to be present? So is there a way to pass through a param for delimiter and use the default for keep_tags?

**Comment by jduss4** [comment]
I tried to clarify this a little in the documentation.  Everything is optional except for the xpath in question.  They do have to be in a particular order, however, so it is impossible to not set the keep_tags if you need to get to the delimiter parameter.  If there is a specific order that we think would be most useful, I am happy to rearrange them as necessary!

I also just added a parameter "xml" so that you can pass in a different xml object if required!
